name: Build and deploy to AWS EB
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create version label
        run: |
          echo "APP_VERSION=$(echo $(date +'%Y-%m-%d-%s') | cut -c 1-6)" >> $GITHUB_ENV
          echo $APP_VERSION

      - name: Build docker image
        run: docker build -t bankonlyx3/terena.office -f Dockerfile .

      - name: Create ZIP file current context
        run: zip -r deploy.zip *

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: terena.office.service
          environment_name: Terenaofficeservice-env
          version_label: "terena.office.service-${{ env.APP_VERSION }}"
          region: ap-southeast-1
          deployment_package: deploy.zip
