name: go-pipeline-demo
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    # needs: test
    # if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: bankonlyx3/terena.office
          tag-custom: latest
          tag-semver: |
            {{raw}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
